name: build

on:
  workflow_dispatch:
  # push:

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [bionic-x64, bionic-arm64, bionic-armhf, centos7-devtoolset8-x64, centos7-devtoolset8-arm64]
        include:
        - arch: centos7-devtoolset8-arm64
          qemu: true

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        if: matrix.qemu == true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.arch }}
          file: ${{ matrix.arch }}/Dockerfile
          tags: gitpod/openvscode-server-linux-build-agent:${{ matrix.arch }}
          push: ${{ github.ref == 'refs/heads/main' }}
