name: build

on:
  workflow_dispatch:
    inputs:
      uploadRelease:
        description: "Create Github Release"
        type: boolean
      tag:
        description: "Github release tag"

jobs:
  generate_toolchain:
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: amd64
            config: x86_64-gcc-8.5.0-glibc-2.28.config
            pkg: x86_64-linux-gnu
          - arch: arm64
            config: aarch64-gcc-8.5.0-glibc-2.28.config
            pkg: aarch64-linux-gnu
          - arch: armhf
            config: armhf-gcc-8.5.0-glibc-2.28.config
            pkg: arm-rpi-linux-gnueabihf
    uses: ./.github/workflows/build-toolchain.yml
    with:
      config: ${{ matrix.config }}
      arch: ${{ matrix.arch }}
      pkg: ${{ matrix.pkg }}

  release_toolchain:
    if: github.event.inputs.uploadRelease == 'true'
    runs-on: ubuntu-latest
    needs: generate_toolchain
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: artifacts/

      - run: |
          mkdir upload

          cp artifacts/amd64/x86_64-linux-gnu.tar.gz upload/x86_64-linux-gnu.tar.gz
          cp artifacts/arm64/aarch64-linux-gnu.tar.gz upload/aarch64-linux-gnu.tar.gz
          cp artifacts/armhf/arm-rpi-linux-gnueabihf.tar.gz upload/arm-rpi-linux-gnueabihf.tar.gz

          cd upload
          shasum -a 256 *.tar.gz > SHASUMS256.txt

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          repository: ${{ github.repository_owner }}/vscode-linux-build-agent
          tag_name: ${{ inputs.tag }}
          token: ${{ secrets.VSCODE_GITHUB_TOKEN }}
          files: upload/*
