name: build

on:
  workflow_dispatch:
  # push:

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [bionic-x64, buster-arm64, buster-armhf, centos7-devtoolset8-x64, centos7-devtoolset8-arm64]

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        if: matrix.qemu == 'true'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.arch }}
          file: ${{ matrix.arch }}/Dockerfile
          tags: gitpod/openvscode-server-linux-build-agent:${{ matrix.arch }}
          push: ${{ github.ref == 'refs/heads/main' }}
